In [1]:
import numpy as np

In [3]:
#1D array
arr1 = np.array([10,20,30,40,50])
print("1D array\n",arr1)
#2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print("2D array\n",arr2)
#3D array
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3D array\n",arr3)
#dimention of array
print("dimention of array\n",arr3.ndim)


1D array
 [10 20 30 40 50]
2D array
 [[1 2 3]
 [4 5 6]]
3D array
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
dimention of array
 3


In [4]:
#array properties
print("\nArray Shape(rows, column):",arr2.shape)
print("\nArray size:",arr2.size)
print("\nArray data type:",arr2.dtype)


Array Shape(rows, column): (2, 3)

Array size: 6

Array data type: int64


In [6]:
#creating arrays with special values
zeros=np.zeros((2,3))
ones=np.ones((3,2))
eye=np.eye(3)
rand=np.random.rand(2,3)
arange_arr=np.arange(0,10,2)
linespace_arr=np.linspace(0,1,5)

print("\nZeros Array\n",zeros)
print("\nOnes Array\n",ones)
print("\nIdentity Array\n",eye)
print("\nRandom Array\n",rand)
print("\nArange Array\n",arange_arr)
print("\nLinespace Array\n",linespace_arr)



Zeros Array
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Array
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Identity Array
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array
 [[0.34246264 0.38566525 0.16507361]
 [0.79809391 0.69475917 0.62801708]]

Arange Array
 [0 2 4 6 8]

Linespace Array
 [0.   0.25 0.5  0.75 1.  ]


In [7]:
arr=np.array([10,20,30,40,50,60])
print("\nOriginal Array:",arr)
print("First Element:",arr[0])
print("Last Element:",arr[-1])
print("Slice[1:4]:",arr[1:4])
print("Every 2nd Element",arr[::2])

#2D Array slicing
arr2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("\nOriginal 2D Array:",arr2d)
print("Element at [1:2]:",arr2d[1:2])
print("First two rows and first two columns:",arr2d[:2,:2])


Original Array: [10 20 30 40 50 60]
First Element: 10
Last Element: 60
Slice[1:4]: [20 30 40]
Every 2nd Element [10 30 50]

Original 2D Array: [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at [1:2]: [[40 50 60]]
First two rows and first two columns: [[10 20]
 [40 50]]


In [8]:
#Statistical and Mathematical Functions
arr=np.array([1,2,3,4,5])
print("\nSum:",np.sum(arr))
print("\nMin:",np.min(arr))
print("\nMax:",np.max(arr))
print("\nMean:",np.mean(arr))
print("\nMedian:",np.median(arr))
print("\nStandard Deviation:",np.std(arr))


Sum: 15

Min: 1

Max: 5

Mean: 3.0

Median: 3.0

Standard Deviation: 1.4142135623730951


In [9]:
#arithmetic operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Exponentiation:",a**2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponentiation: [1 4 9]


In [ ]:
#for 2D arrays
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("\nSum:",np.sum(arr))
print("\nMin:",np.min(arr))
print("\nMax:",np.max(arr))
print("\nMean:",np.mean(arr))
print("\nMedian:",np.median(arr))
print("\nStandard Deviation:",np.std(arr))

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[4,5,6],[7,8,9]])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Exponentiation:",a**2)


Sum: 55

Min: 1

Max: 10

Mean: 5.5

Median: 5.5

Standard Deviation: 2.8722813232690143
Addition: [[ 5  7  9]
 [11 13 15]]
Subtraction: [[-3 -3 -3]
 [-3 -3 -3]]
Multiplication: [[ 4 10 18]
 [28 40 54]]
Division: [[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]
Exponentiation: [[ 1  4  9]
 [16 25 36]]


In [14]:
#reshaping and flatning
arr=np.arange(1,13)
print("\nOriginal array:\n",arr)
reshaped=arr.reshape(3,4)
print("\nReshaped to 3x4 array:\n",reshaped)
flat=reshaped.flatten()
print("\nFlattened back to 1D array:\n",flat)


Original array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened back to 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
#concatination and stacking
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print("\nHorizontal Stack:",np.hstack((x,y)))
print("\nVertical Stack:",np.vstack((x,y)))


Horizontal Stack: [[1 2 5 6]
 [3 4 7 8]]

Vertical Stack: [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
#Boolean Indexing and Filtering
arr=np.array([5,10,15,20,25,30])
filter_arr=arr>15
print("\nFilter Boolean Array:",filter_arr)
print("Filtered Vaues (arr > 15);",arr[filter_arr])


Filter Boolean Array: [False False False  True  True  True]
Filtered Vaues (arr > 15); [20 25 30]
