In [7]:
import tensorflow as tf

# Question 1
# Create a scalar tensor with value 10
scalar = tf.constant(10)
print("Q1 Scalar value:", scalar)
print("Q1 Data type:", scalar.dtype)


Q1 Scalar value: tf.Tensor(10, shape=(), dtype=int32)
Q1 Data type: <dtype: 'int32'>


In [8]:
# Question 2
# Create a 1-D tensor (vector)
vector = tf.constant([2, 4, 6, 8])
print("\nQ2 Vector shape:", vector.shape)
print("Q2 Vector numpy value:", vector.numpy())


Q2 Vector shape: (4,)
Q2 Vector numpy value: [2 4 6 8]


In [9]:
# Question 3
# Create a 2-D tensor (matrix)
matrix = tf.constant([[1, 2], [3, 4]])
print("\nQ3 Matrix shape:", matrix.shape)
print("Q3 Matrix dtype:", matrix.dtype)


Q3 Matrix shape: (2, 2)
Q3 Matrix dtype: <dtype: 'int32'>


In [10]:
# Question 4
# Create a tf.Variable
var = tf.Variable(5.0)
print("\nQ4 Variable value:", var.numpy())


Q4 Variable value: 5.0


In [11]:
# Question 5
# Update variable using assign()
var.assign(10.0)
print("\nQ5 Updated variable value:", var.numpy())


Q5 Updated variable value: 10.0


In [12]:
# Question 6 
var_matrix = tf.Variable([[1.0, 2.0],
                          [3.0, 4.0]])

var_matrix.assign_add(tf.ones_like(var_matrix))

print("Matrix after assign_add:")
print(var_matrix.numpy())


Matrix after assign_add:
[[2. 3.]
 [4. 5.]]


In [13]:
# Question 7
# Compute y inside GradientTape
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x**2 + 2*x + 1

print("\nQ7 x value:", x.numpy())
print("Q7 y value:", y.numpy())


Q7 x value: 3.0
Q7 y value: 16.0


In [14]:
# Question 8
# Compute gradient dy/dx
gradient = tape.gradient(y, x)
print("\nQ8 Gradient dy/dx:", gradient.numpy())


Q8 Gradient dy/dx: 8.0


In [15]:
# Question 9
# Matrix multiplication
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
matmul_result = tf.matmul(a, b)

print("\nQ9 Matrix multiplication result:")
print(matmul_result.numpy())


Q9 Matrix multiplication result:
[[19 22]
 [43 50]]


In [16]:
# Question 10
# Random tensor using tf.random.uniform
random_tensor = tf.random.uniform((3, 3))
print("\nQ10 Random tensor shape:", random_tensor.shape)
print("Q10 Random tensor dtype:", random_tensor.dtype)
print("Q10 Random tensor values:")
print(random_tensor.numpy())


Q10 Random tensor shape: (3, 3)
Q10 Random tensor dtype: <dtype: 'float32'>
Q10 Random tensor values:
[[0.43186128 0.5818813  0.4866786 ]
 [0.6197643  0.6587658  0.41820467]
 [0.19422698 0.8675616  0.14420724]]
